export const ErrorCodes = {
    AUTH_REQUIRED: 'AUTH_REQUIRED',

    INVALID_TOKEN: 'INVALID_TOKEN',

    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',

    WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',

    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',

    TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',

    INVALID_AMOUNT: 'INVALID_AMOUNT',

    BLOCKCHAIN_ERROR: 'BLOCKCHAIN_ERROR',
} as const;
