services:
  postgres:
    image: postgres:16
    container_name: mini-tether-postgres
    environment:
      POSTGRES_USER: tether
      POSTGRES_PASSWORD: tether
      POSTGRES_DB: mini_tether
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: blockchain-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data: